### PR TITLE
Added the ability to call github with OAuth.  This prevents the 60 user-rate limit issue

### PR DESCRIPTION
**Pull request by Dantheman720**
DO NOT MERGE - There is currently an issue with the github token.  I tested this a couple of times locally and get a "bad request" from github.

### CODE REVIEW

**Comment by LightGuard** [comment]
This is OAuth, right? Shouldn't we be sending the token as a header? If so, we should do that after we create the connection and have it be connection wide.

**Comment by Dantheman720** [comment]
@LightGuard @paulrobinson , the header would probably be the cleanest way to do it, but wouldn't it require quite a bit of refactoring in aweplug?  Also, I can't seem to get the environment variable for the github access token on the pull-play executor to work with any sort of authentication.  I must be doing something wrong.  I have tried both to no avail--with the token in place of OAUTH-TOKEN of course :)   

curl -H "Authorization: token OAUTH-TOKEN" https://api.github.com/users/technoweenie -I
curl https://api.github.com/user?access_token=OAUTH-TOKEN

However, when I use the token that I generated on my personal github account, they work.  I'm likely being dense and overlooking something here...

**Comment by LightGuard** [comment]
When you create a `Faraday::Connection`, hopefully with the helper, it returns back the `Connection` object which you can use then to add headers to which will be used for each request, it shouldn't be terribly complicated. Pretty sure we've done this in other parts of the project.

Does the CI environment have the ENV set for the token?

**Comment by Dantheman720** [comment]
Yeah, the CI environment does have a token.  I am having difficulty adding the token to the request header.  I plan to return to it tomorrow.

**Comment by Dantheman720** [comment]
@paulrobinson @LightGuard  Paul and I discussed this and it seems that the best solution is to append the token.  There are only three places where it is required and it seems like setting it in the header would cause issues with Google-apis and whatnot.

**Comment by LightGuard** [comment]
Close?

**Comment by Dantheman720** [comment]
This is the appended URI and can be closed.

**Pull request closed without merging**
