### PR TITLE
DEVELOPER-1318 404s being returned from github during demo creation does...

### PR DESCRIPTION
**Pull request by Dantheman720**
... not fail the build

### CODE REVIEW

**Comment by Dantheman720** [comment]
@LightGuard I tested this and it throws the error when 'content' isn't available.

**Comment by LightGuard** [comment]
This isn't going to work. You need to check the return / successful / status (successful? would be better because it checks all of the status codes). If it's successful, then use the body, This also fails if what's returned isn't nil (or at least it should), maybe it's some 404 page, or 404 json return that makes things look bad on the site like http://www.jboss.org//demos/servlets/index.html for example. In that example what was returned was "Not Found". That's actually valid JSON, but not what we want.

**Comment by LightGuard** [comment]
I'm happy with this. Thanks Dan!

**Comment by Dantheman720** [comment]
Woot!  Good deal.

**Pull request merged**
